apiVersion: v1
kind: Service
metadata:
  name: kafkademo
spec:
  type: LoadBalancer
  selector:
    app: kafkademo
  ports:
    - name: kafkademoport
      protocol: TCP
      port: 8080
      targetPort: 8080